version: "3"
services:

  portainer:
    image: portainer/portainer-ce:2.18.4
    container_name: Portainer
    ports:
      - "${PORTAINER_PORT:-9443}:${PORTAINER_PORT:-9443}"
    volumes:
      - portainer:/data/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_net
    restart: unless-stopped

  postgres:
    container_name: Postgres
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - app_net
    restart: unless-stopped
  
  pgadmin:
    container_name: pgAdmin4
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@strypes.pt}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app_net
    restart: unless-stopped

  streamlit:
    container_name: Streamlit
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    volumes:
       - streamlit:/data/streamlit
    ports:
      - "${STREAMLIT_PRD_PORT:-8501}:${STREAMLIT_PRD_PORT:-8501}"
    depends_on:
      - postgres
    networks:
      - app_net

  streamlit_dev:
    container_name: StreamlitDev
    profiles: ["dev"]
    build:
      context: .
      dockerfile: streamlit.dev.Dockerfile
    volumes:
       - streamlitdev:/data/streamlit
       - ../app/:/app
    ports:
      - "${STREAMLIT_DEV_PORT:-8502}:${STREAMLIT_DEV_PORT:-8502}"
    depends_on:
      - postgres
    networks:
      - app_net
    
networks:
  app_net:
    driver: bridge

volumes:
  portainer:
  postgres:
  pgadmin:
  streamlit:
  streamlitdev: